# Generated by Django 5.1.2 on 2025-01-09 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_shoesize_product_available_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='available_sizes',
            field=models.ManyToManyField(blank=True, to='product.shoesize'),
        ),
    ]
