# Generated by Django 5.1.2 on 2025-03-09 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_bio_profile_date_of_birth_profile_email_and_more'),
        ('product', '0010_pickupstation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.pickupstation'),
        ),
    ]
