# Generated by Django 5.1.2 on 2025-01-06 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0026_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='FWZU28U7', max_length=20),
        ),
    ]
