# Generated by Django 5.1.2 on 2025-01-06 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='STFHSXL8', max_length=20),
        ),
    ]
