# Generated by Django 5.1.2 on 2025-01-08 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='7PLMA7VY', max_length=20),
        ),
    ]
