# Generated by Django 5.1.2 on 2025-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0033_alter_order_code_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='0YJTCS7L', max_length=20),
        ),
    ]
