# Generated by Django 5.1.2 on 2025-01-08 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0034_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='QQ2YKJ56', max_length=20),
        ),
    ]
