# Generated by Django 5.1.2 on 2025-03-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_order_mpesa_checkout_id_order_mpesa_receipt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='X00Y45NK', max_length=20),
        ),
    ]
