# Generated by Django 5.1.2 on 2025-03-03 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0041_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='AJA30PPO', max_length=20),
        ),
    ]
