# Generated by Django 5.1.2 on 2025-03-03 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0043_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartdetail',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='S9AOHK4X', max_length=20),
        ),
    ]
