# Generated by Django 5.1.2 on 2025-03-04 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0044_cartdetail_size_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='3HLPGY9O', max_length=20),
        ),
    ]
