# Generated by Django 5.1.2 on 2025-03-04 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0045_alter_order_code'),
        ('product', '0010_pickupstation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pickup_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.pickupstation'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='GP2JZBYL', max_length=20),
        ),
    ]
