# Generated by Django 5.1.2 on 2025-03-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0046_order_pickup_station_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='53NTGRNK', max_length=20),
        ),
    ]
