# Generated by Django 5.1.2 on 2025-03-04 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0047_order_delivery_fee_alter_order_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='J9MQ0RAD', max_length=20),
        ),
    ]
