# Generated by Django 5.1.2 on 2025-03-05 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0048_order_delivery_end_date_order_delivery_start_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='8L58XO23', max_length=20),
        ),
    ]
