# Generated by Django 5.1.2 on 2025-03-05 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='MUCBE5K0', max_length=20),
        ),
    ]
