# Generated by Django 5.1.2 on 2025-03-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0051_order_total_price_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='O1SWXM5A', max_length=20),
        ),
    ]
