# Generated by Django 5.1.2 on 2025-03-05 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_alter_order_code_alter_transaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='QMZE1YRK', max_length=20, unique=True),
        ),
    ]
