# Generated by Django 5.1.2 on 2025-03-06 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_alter_order_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reference', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('account_number', models.CharField(default='0757790687', max_length=50)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('checkout_request_id', models.CharField(blank=True, max_length=50)),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
