# Generated by Django 5.1.2 on 2025-03-06 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0058_mpesapayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
