# Generated by Django 5.1.2 on 2025-03-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0059_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='checkout_request_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='mpesa_receipt_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
