# Generated by Django 5.1.2 on 2025-03-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0060_transaction_checkout_request_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='size',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
